// Auto-generated from Tiger's curated catalogue — do not edit manually
module.exports = [
  {
    "id": "base_001",
    "title": "Introducing Quantum Theory",
    "author": "J.P. McEvoy & Oscar Zarate",
    "genre": "Science",
    "type": "Non-Fiction",
    "year": 1996,
    "nation": "🇬🇧 United Kingdom",
    "description": "A visually engaging comic-book introduction to quantum mechanics, tracing its development from Planck to Schrödinger. Ideal for the curious non-scientist.",
    "is_sikkim": 0
  },
  {
    "id": "base_002",
    "title": "Persepolis",
    "author": "Marjane Satrapi",
    "genre": "Graphic Novel",
    "type": "Fiction",
    "year": 2000,
    "nation": "🇮🇷 Iran / 🇫🇷 France",
    "description": "An iconic graphic memoir of growing up during the Islamic Revolution in Iran — candid, humorous, and deeply political. One of the great coming-of-age stories of the 21st century.",
    "is_sikkim": 0
  },
  {
    "id": "base_003",
    "title": "Jerusalem",
    "author": "Guy Delisle",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2011,
    "nation": "🇨🇦 Canada",
    "description": "A year spent in Jerusalem with Médecins Sans Frontières — a nuanced outsider's perspective on one of the world's most contested cities.",
    "is_sikkim": 0
  },
  {
    "id": "base_004",
    "title": "Logicomix",
    "author": "Apostolos Doxiadis & Christos Papadimitriou",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2009,
    "nation": "🇬🇷 Greece",
    "description": "An epic graphic novel following Bertrand Russell's quest for the logical foundations of mathematics — philosophy, history, and biography with extraordinary elegance.",
    "is_sikkim": 0
  },
  {
    "id": "base_005",
    "title": "The Librarian of Auschwitz",
    "author": "Antonio Iturbe",
    "genre": "History",
    "type": "Fiction",
    "year": 2012,
    "nation": "🇪🇸 Spain",
    "description": "The astonishing true story of Dita Kraus, who secretly kept a small library alive inside Auschwitz-Birkenau. A testament to the power of literature against annihilation.",
    "is_sikkim": 0
  },
  {
    "id": "base_006",
    "title": "The Beatles: All Our Yesterdays",
    "author": "Jason Quinn & Lalit Kumar Sharma",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2013,
    "nation": "🇮🇳 India",
    "description": "Campfire's illustrated biography of the Fab Four, charting their rise from Liverpool to global phenomenon.",
    "is_sikkim": 0
  },
  {
    "id": "base_007",
    "title": "They Changed the World: Crick & Watson",
    "author": "Rik Hoskin & Naresh Kumar",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2012,
    "nation": "🇮🇳 India",
    "description": "The graphic account of the race to discover the double helix — science, ambition, and the ethics of discovery.",
    "is_sikkim": 0
  },
  {
    "id": "base_008",
    "title": "They Changed the World: Copernicus, Bruno & Galileo",
    "author": "Nalini Ramachandran",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2012,
    "nation": "🇮🇳 India",
    "description": "Three revolutionaries who upended humanity's place in the cosmos — a vivid Campfire retelling of the birth of modern astronomy.",
    "is_sikkim": 0
  },
  {
    "id": "base_009",
    "title": "Abdul Kalam: One Man, Many Missions",
    "author": "Lewis Helfand & Naresh Kumar",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2010,
    "nation": "🇮🇳 India",
    "description": "The inspiring life of India's Missile Man and People's President — from Rameswaram to ISRO's launch pads and Rashtrapati Bhavan.",
    "is_sikkim": 0
  },
  {
    "id": "base_010",
    "title": "The Industrial Revolution",
    "author": "Lewis Helfand",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2013,
    "nation": "🇮🇳 India",
    "description": "Campfire's sweeping graphic account of the era that transformed the world — steam, factories, labour, and the birth of modernity.",
    "is_sikkim": 0
  },
  {
    "id": "base_011",
    "title": "The Wright Brothers",
    "author": "Campfire",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2012,
    "nation": "🇮🇳 India",
    "description": "The story of Orville and Wilbur Wright's relentless pursuit of powered flight — one of history's great narratives of persistence and invention.",
    "is_sikkim": 0
  },
  {
    "id": "base_012",
    "title": "Chanakya",
    "author": "James Peaty & Rajesh Nagulakonda",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2013,
    "nation": "🇮🇳 India",
    "description": "An illustrated biography of ancient India's master strategist, philosopher, and kingmaker — the original student of power.",
    "is_sikkim": 0
  },
  {
    "id": "base_013",
    "title": "World War Two: Against the Rising Sun",
    "author": "Jason Quinn & Naresh Kumar",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2012,
    "nation": "🇮🇳 India",
    "description": "Campfire's graphic retelling of the Pacific theatre of WWII — Japan's imperial expansion and the Allied fightback.",
    "is_sikkim": 0
  },
  {
    "id": "base_014",
    "title": "World War One: 1914–1918",
    "author": "Alan Cowsill & Lalit Kumar Sharma",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2013,
    "nation": "🇮🇳 India",
    "description": "The Great War in graphic form — trenches, diplomacy, and the catastrophic reshaping of the modern world order.",
    "is_sikkim": 0
  },
  {
    "id": "base_015",
    "title": "Gandhi: My Life Is My Message",
    "author": "Jason Quinn & Sachin Nagar",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2011,
    "nation": "🇮🇳 India",
    "description": "A reverent graphic biography of the Mahatma — from South Africa's railways to India's independence.",
    "is_sikkim": 0
  },
  {
    "id": "base_016",
    "title": "Martin Luther King Jr: Let Freedom Ring",
    "author": "Michael Teitelbaum & Lewis Helfand",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2011,
    "nation": "🇮🇳 India",
    "description": "The civil rights leader's life and dream, rendered in powerful graphic form.",
    "is_sikkim": 0
  },
  {
    "id": "base_017",
    "title": "Conquering Everest",
    "author": "Lewis Helfand",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2011,
    "nation": "🇮🇳 India",
    "description": "The legendary 1953 first ascent of Hillary and Tenzing Norgay — breathtaking scale and human drama on the world's highest peak.",
    "is_sikkim": 0
  },
  {
    "id": "base_018",
    "title": "Abraham Lincoln: From the Log Cabin to the White House",
    "author": "Lewis Helfand",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2012,
    "nation": "🇮🇳 India",
    "description": "Lincoln's extraordinary journey — from frontier poverty to leading a nation through its bloodiest war.",
    "is_sikkim": 0
  },
  {
    "id": "base_019",
    "title": "Muhammad Ali: The King of the Ring",
    "author": "Jason Quinn",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2012,
    "nation": "🇮🇳 India",
    "description": "The Greatest's life told in graphic glory — from Louisville to Kinshasa, boxing, activism, and unshakeable conviction.",
    "is_sikkim": 0
  },
  {
    "id": "base_020",
    "title": "Steve Jobs: Genius by Design",
    "author": "Lewis Helfand",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2012,
    "nation": "🇮🇳 India",
    "description": "Apple's mercurial co-founder in graphic biography — vision, perfectionism, and the products that changed everyday life.",
    "is_sikkim": 0
  },
  {
    "id": "base_021",
    "title": "They Changed the World: Edison, Tesla & Bell",
    "author": "Kieron Moore & Sachin Nagar",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2013,
    "nation": "🇮🇳 India",
    "description": "Three titans of invention who electrified and connected the modern world — their rivalries and breakthroughs in sequential art.",
    "is_sikkim": 0
  },
  {
    "id": "base_022",
    "title": "Ambedkar: India's Crusader for Human Rights",
    "author": "Lewis Helfand",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2010,
    "nation": "🇮🇳 India",
    "description": "The life and legacy of Dr. B.R. Ambedkar — jurist, economist, social reformer, and architect of India's Constitution.",
    "is_sikkim": 0
  },
  {
    "id": "base_023",
    "title": "Nelson Mandela (Campfire)",
    "author": "Lewis Helfand",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2010,
    "nation": "🇮🇳 India",
    "description": "Madiba's extraordinary life — from anti-apartheid activist to Robben Island prisoner to South Africa's first democratically elected president.",
    "is_sikkim": 0
  },
  {
    "id": "base_024",
    "title": "Notes from a Defeatist",
    "author": "Joe Sacco",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2003,
    "nation": "🇺🇸 USA / 🇲🇹 Malta",
    "description": "Sacco's early, darkly funny comics — journalism, self-deprecation, and social observation before his iconic war reporting.",
    "is_sikkim": 0
  },
  {
    "id": "base_025",
    "title": "Paying the Land",
    "author": "Joe Sacco",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2020,
    "nation": "🇺🇸 USA / 🇲🇹 Malta",
    "description": "Sacco turns his graphic journalism to Canada's Northwest Territories and the Dene Nation — land, oil pipelines, and Indigenous sovereignty.",
    "is_sikkim": 0
  },
  {
    "id": "base_026",
    "title": "Palestine",
    "author": "Joe Sacco",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 1996,
    "nation": "🇺🇸 USA / 🇲🇹 Malta",
    "description": "The landmark graphic-journalism work — two months in the West Bank and Gaza, rendered in extraordinary documentary detail.",
    "is_sikkim": 0
  },
  {
    "id": "base_027",
    "title": "The Complete Maus",
    "author": "Art Spiegelman",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 1991,
    "nation": "🇺🇸 USA",
    "description": "The Pulitzer-winning masterpiece depicting Holocaust survival through mice and cats. A monument of 20th-century literature.",
    "is_sikkim": 0
  },
  {
    "id": "base_028",
    "title": "Sapiens: A Graphic History Vol. 1",
    "author": "Yuval Noah Harari",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2020,
    "nation": "🇮🇱 Israel",
    "description": "The graphic adaptation of Harari's global bestseller — the birth of humankind, the Cognitive Revolution, and our conquest of the planet.",
    "is_sikkim": 0
  },
  {
    "id": "base_029",
    "title": "Sapiens: A Graphic History Vol. 2",
    "author": "Yuval Noah Harari",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2021,
    "nation": "🇮🇱 Israel",
    "description": "The second volume — the Agricultural Revolution and the new stories and hierarchies it created across human civilisation.",
    "is_sikkim": 0
  },
  {
    "id": "base_030",
    "title": "First Hand Volume 2: Exclusion",
    "author": "Various",
    "genre": "Graphic Novel",
    "type": "Non-Fiction",
    "year": 2020,
    "nation": "🇮🇳 India",
    "description": "An anthology of graphic short stories exploring lived experiences of marginalisation, identity, and exclusion in contemporary India.",
    "is_sikkim": 0
  },
  {
    "id": "base_031",
    "title": "To Kill a Mockingbird (Graphic Novel)",
    "author": "Harper Lee / Fred Fordham",
    "genre": "Graphic Novel",
    "type": "Fiction",
    "year": 2018,
    "nation": "🇺🇸 USA",
    "description": "The beloved Pulitzer-winning novel adapted into graphic form — Atticus Finch, racial injustice, and the moral education of Scout in Depression-era Alabama.",
    "is_sikkim": 0
  },
  {
    "id": "base_032",
    "title": "Bhagavad Gita: Commentary by Swami Mukundananda",
    "author": "Swami Mukundananda",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 2013,
    "nation": "🇮🇳 India",
    "description": "A comprehensive verse-by-verse commentary on the Song of God — drawing on the Ramanujacharya tradition with practical guidance for modern seekers.",
    "is_sikkim": 0
  },
  {
    "id": "base_033",
    "title": "Ishavasya Upanishad",
    "author": "Swami Mukundananda",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 2015,
    "nation": "🇮🇳 India",
    "description": "A commentary on one of the shortest yet most profound Upanishads — the vision of the divine pervading all creation.",
    "is_sikkim": 0
  },
  {
    "id": "base_034",
    "title": "The Rig Veda",
    "author": "Various (trans. Wendy Doniger)",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 1981,
    "nation": "🇮🇳 India",
    "description": "A selection from the world's oldest surviving religious literature — Vedic hymns rendered in accessible English with scholarly notes.",
    "is_sikkim": 0
  },
  {
    "id": "base_035",
    "title": "Gita (Devdutt Pattanaik)",
    "author": "Devdutt Pattanaik",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 2011,
    "nation": "🇮🇳 India",
    "description": "Pattanaik's accessible retelling of the Bhagavad Gita — a timeless philosophical conversation about action, duty, and the self.",
    "is_sikkim": 0
  },
  {
    "id": "base_036",
    "title": "Hanuman: Chalisa",
    "author": "Devdutt Pattanaik",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 2015,
    "nation": "🇮🇳 India",
    "description": "A verse-by-verse exploration of Tulsidas's devotional masterpiece — the mythology and spiritual significance of Hanuman's forty verses.",
    "is_sikkim": 0
  },
  {
    "id": "base_037",
    "title": "7 Secrets of Shiva",
    "author": "Devdutt Pattanaik",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 2011,
    "nation": "🇮🇳 India",
    "description": "Pattanaik unlocks Shiva's iconography — his matted hair, third eye, crescent moon, and trident as keys to a profound philosophical worldview.",
    "is_sikkim": 0
  },
  {
    "id": "base_038",
    "title": "7 Secrets of Vishnu",
    "author": "Devdutt Pattanaik",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 2011,
    "nation": "🇮🇳 India",
    "description": "Vishnu's avatars, consorts, and symbols as a coherent system of thought about preservation, compassion, and cosmic order.",
    "is_sikkim": 0
  },
  {
    "id": "base_039",
    "title": "112 Meditations for Self Realisation",
    "author": "Vigyan Bhairav Tantra",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 2012,
    "nation": "🇮🇳 India",
    "description": "One hundred and twelve meditation techniques from the ancient Shaiva text — Shiva's answers to Devi on the pathways to transcendence.",
    "is_sikkim": 0
  },
  {
    "id": "base_040",
    "title": "Stages of Meditation",
    "author": "Rabindranath Tagore",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 2001,
    "nation": "🇮🇳 India",
    "description": "A commentary on Kamalashila's classical Buddhist text — adapted with the poet-philosopher Tagore's characteristic spiritual grace.",
    "is_sikkim": 0
  },
  {
    "id": "base_041",
    "title": "Avatars of Brahma",
    "author": "Joseph Noyon",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 2012,
    "nation": "🇮🇳 India",
    "description": "An exploration of the Brahma tradition in Indian spiritual thought — lesser-known stories of the creator in the Hindu trinity.",
    "is_sikkim": 0
  },
  {
    "id": "base_042",
    "title": "The Art of Happiness",
    "author": "Dalai Lama & Howard C. Cutler",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 1998,
    "nation": "🇮🇳 India / 🇺🇸 USA",
    "description": "His Holiness in conversation with an American psychiatrist — Buddhist wisdom applied to the universal human pursuit of happiness.",
    "is_sikkim": 0
  },
  {
    "id": "base_043",
    "title": "The Illustrated Buddha for Beginners",
    "author": "Asma",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 2010,
    "nation": "🇺🇸 USA",
    "description": "A visually rich introduction to the life of the Buddha and core Buddhist teachings — accessible, illustrated, and elegantly presented.",
    "is_sikkim": 0
  },
  {
    "id": "base_044",
    "title": "The Power of One Thought",
    "author": "BK Shivani",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 2019,
    "nation": "🇮🇳 India",
    "description": "Sister Shivani of Brahma Kumaris shares practical tools for transforming thought quality — the foundation of emotional wellbeing.",
    "is_sikkim": 0
  },
  {
    "id": "base_045",
    "title": "The Complete Book of Yoga",
    "author": "Swami Vivekananda",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 2012,
    "nation": "🇮🇳 India",
    "description": "Vivekananda's exposition of the four paths of yoga — Karma, Jnana, Bhakti, and Raja — from his canonical lectures.",
    "is_sikkim": 0
  },
  {
    "id": "base_046",
    "title": "My Wisdom Book",
    "author": "Swami Mukundananda",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 2018,
    "nation": "🇮🇳 India",
    "description": "A treasury of spiritual aphorisms and practical wisdom — distilled teachings on the mind, devotion, and inner transformation.",
    "is_sikkim": 0
  },
  {
    "id": "base_047",
    "title": "Dying to Be Me",
    "author": "Anita Moorjani",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 2012,
    "nation": "🇮🇳 India / 🇺🇸 USA",
    "description": "Moorjani's near-death experience from terminal cancer and miraculous recovery — a profound shift in consciousness and self-love.",
    "is_sikkim": 0
  },
  {
    "id": "base_048",
    "title": "Karma",
    "author": "Sadhguru",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 2021,
    "nation": "🇮🇳 India",
    "description": "Sadhguru's guide to karma — not as fate but as the memory and momentum of action, and how to use it as a tool for conscious living.",
    "is_sikkim": 0
  },
  {
    "id": "base_049",
    "title": "Religion Gone Astray",
    "author": "Don Mackenzie, Ted Falcon & Jamal Rahman",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 2011,
    "nation": "🇺🇸 USA",
    "description": "Three clergy — a pastor, a rabbi, and an imam — examine the dark sides of their own traditions and chart a path toward interfaith understanding.",
    "is_sikkim": 0
  },
  {
    "id": "base_050",
    "title": "Garuda Purana",
    "author": "Devdutt Pattanaik",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 2014,
    "nation": "🇮🇳 India",
    "description": "Pattanaik's retelling of the Garuda Purana — Hindu scripture on death, the afterlife, and the journey of the soul, demystified.",
    "is_sikkim": 0
  },
  {
    "id": "base_051",
    "title": "Jaya: An Illustrated Retelling of the Mahabharata",
    "author": "Devdutt Pattanaik",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2010,
    "nation": "🇮🇳 India",
    "description": "Pattanaik's celebrated retelling of the world's longest epic — Kurukshetra, dharma, desire, and the infinite complexity of the Mahabharata.",
    "is_sikkim": 0
  },
  {
    "id": "base_052",
    "title": "Norwegian Wood",
    "author": "Haruki Murakami",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 1987,
    "nation": "🇯🇵 Japan",
    "description": "Murakami's most intimate novel — a tender, melancholic portrait of loss, first love, and the loneliness of Tokyo's 1960s counterculture generation.",
    "is_sikkim": 0
  },
  {
    "id": "base_053",
    "title": "Kafka on the Shore",
    "author": "Haruki Murakami",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2002,
    "nation": "🇯🇵 Japan",
    "description": "Two narratives weave toward each other in this dazzling metaphysical odyssey through fate, memory, and the strangeness of the everyday.",
    "is_sikkim": 0
  },
  {
    "id": "base_054",
    "title": "The Wind-Up Bird Chronicle",
    "author": "Haruki Murakami",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 1994,
    "nation": "🇯🇵 Japan",
    "description": "A missing cat and a missing wife draw an ordinary Tokyo man into the dark underworld of Japan's history and the self.",
    "is_sikkim": 0
  },
  {
    "id": "base_055",
    "title": "1Q84",
    "author": "Haruki Murakami",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2009,
    "nation": "🇯🇵 Japan",
    "description": "A parallel Tokyo, two moons in the sky, and an assassin and a novelist drawn together across fractured reality — Murakami's most ambitious work.",
    "is_sikkim": 0
  },
  {
    "id": "base_056",
    "title": "The Complete Trilogy (1Q84)",
    "author": "Haruki Murakami",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2011,
    "nation": "🇯🇵 Japan",
    "description": "The complete 1Q84 trilogy in one volume — the full sweep of Aomame and Tengo's fated, surreal story.",
    "is_sikkim": 0
  },
  {
    "id": "base_057",
    "title": "Men Without Women",
    "author": "Haruki Murakami",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2014,
    "nation": "🇯🇵 Japan",
    "description": "Seven quietly devastating short stories about solitude, loss, and the particular loneliness of men left behind.",
    "is_sikkim": 0
  },
  {
    "id": "base_058",
    "title": "First Person Singular",
    "author": "Haruki Murakami",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2020,
    "nation": "🇯🇵 Japan",
    "description": "Eight tales about memory, music, and the mysteries that accumulate in a lifetime, narrated with Murakami's signature wistful precision.",
    "is_sikkim": 0
  },
  {
    "id": "base_059",
    "title": "The God of Small Things",
    "author": "Arundhati Roy",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 1997,
    "nation": "🇮🇳 India",
    "description": "The Booker Prize-winning debut — forbidden love, caste, and family secrets in Kerala, told in Roy's luminous, original prose.",
    "is_sikkim": 0
  },
  {
    "id": "base_060",
    "title": "Pachinko",
    "author": "Min Jin Lee",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2017,
    "nation": "🇰🇷 South Korea / 🇺🇸 USA",
    "description": "An epic multigenerational saga of a Korean family in Japan — love, sacrifice, identity, and the weight of history across four generations.",
    "is_sikkim": 0
  },
  {
    "id": "base_061",
    "title": "Catch-22",
    "author": "Joseph Heller",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 1961,
    "nation": "🇺🇸 USA",
    "description": "The definitive anti-war novel — Yossarian's surreal, hilarious, horrifying attempts to escape a WWII air base. The paradox that named a generation.",
    "is_sikkim": 0
  },
  {
    "id": "base_062",
    "title": "The Joy Luck Club",
    "author": "Amy Tan",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 1989,
    "nation": "🇺🇸 USA",
    "description": "Four Chinese mothers, four American daughters navigate the painful gap between old China and the new world.",
    "is_sikkim": 0
  },
  {
    "id": "base_063",
    "title": "The Lowland",
    "author": "Jhumpa Lahiri",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2013,
    "nation": "🇮🇳 India / 🇺🇸 USA",
    "description": "Two brothers — one a Naxalite martyr, one an émigré scientist — and the woman between them, spanning Calcutta to Rhode Island.",
    "is_sikkim": 0
  },
  {
    "id": "base_064",
    "title": "The Forty Rules of Love",
    "author": "Elif Shafak",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2009,
    "nation": "🇹🇷 Turkey",
    "description": "The mystical friendship of Rumi and Shams of Tabriz — and its modern mirror in Massachusetts. A love story spanning seven centuries.",
    "is_sikkim": 0
  },
  {
    "id": "base_065",
    "title": "The Little Prince",
    "author": "Antoine de Saint-Exupéry",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 1943,
    "nation": "🇫🇷 France",
    "description": "The beloved French philosophical fable — a boy from a tiny planet illuminates love, loneliness, and what it means to truly see.",
    "is_sikkim": 0
  },
  {
    "id": "base_066",
    "title": "Good Night Stories for Rebel Girls",
    "author": "Elena Favilli & Francesca Cavallo",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2016,
    "nation": "🇮🇹 Italy / 🇺🇸 USA",
    "description": "One hundred bedtime stories of extraordinary women — scientists, artists, warriors, and dreamers from across history.",
    "is_sikkim": 0
  },
  {
    "id": "base_067",
    "title": "Unaccustomed Earth",
    "author": "Jhumpa Lahiri",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2008,
    "nation": "🇮🇳 India / 🇺🇸 USA",
    "description": "Eight masterly stories of second-generation Indian-Americans navigating the distance between their parents' world and their own.",
    "is_sikkim": 0
  },
  {
    "id": "base_068",
    "title": "Malgudi Adventures",
    "author": "R.K. Narayan",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2005,
    "nation": "🇮🇳 India",
    "description": "Tales from Narayan's beloved fictional South Indian town — gentle, humorous, and profoundly human.",
    "is_sikkim": 0
  },
  {
    "id": "base_069",
    "title": "Rhododendrons in the Mist",
    "author": "Ruskin Bond",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2020,
    "nation": "🇮🇳 India",
    "description": "Bond's lovingly crafted Himalayan stories — quiet, tender, and luminous with the mist and pines of his mountain world.",
    "is_sikkim": 1
  },
  {
    "id": "base_070",
    "title": "The Golden Notebook",
    "author": "Doris Lessing",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 1962,
    "nation": "🇬🇧 United Kingdom",
    "description": "Nobel laureate Lessing's landmark feminist novel — a writer keeping four notebooks, each a different lens on her fractured life and world.",
    "is_sikkim": 0
  },
  {
    "id": "base_071",
    "title": "Inferno",
    "author": "Dan Brown",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2013,
    "nation": "🇺🇸 USA",
    "description": "Robert Langdon races through Florence, Venice, and Istanbul in a high-stakes thriller woven around Dante's Divine Comedy.",
    "is_sikkim": 0
  },
  {
    "id": "base_072",
    "title": "Before the Coffee Gets Cold",
    "author": "Toshikazu Kawaguchi",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2015,
    "nation": "🇯🇵 Japan",
    "description": "In a small Tokyo café, customers can travel back in time — but only under strict rules. A meditation on memory, regret, and the unsaid.",
    "is_sikkim": 0
  },
  {
    "id": "base_073",
    "title": "Karnali Blues",
    "author": "Buddhisagar",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2012,
    "nation": "🇳🇵 Nepal",
    "description": "A celebrated Nepali novel — a son's journey to meet his ailing father, a lyrical meditation on memory and rivers.",
    "is_sikkim": 1
  },
  {
    "id": "base_074",
    "title": "The Nine-Chambered Heart",
    "author": "Janice Pariat",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2017,
    "nation": "🇮🇳 India",
    "description": "Nine voices, nine loves — each chapter a different narrator revealing their experience of one elusive woman. From Meghalaya with love.",
    "is_sikkim": 0
  },
  {
    "id": "base_075",
    "title": "Oath of the Vayuputras",
    "author": "Amish Tripathi",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2013,
    "nation": "🇮🇳 India",
    "description": "The thrilling conclusion to the Shiva Trilogy — the war for Meluha's future and Shiva's final sacrifice.",
    "is_sikkim": 0
  },
  {
    "id": "base_076",
    "title": "Something I Never Told You",
    "author": "Shravya Bhinder",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2017,
    "nation": "🇮🇳 India",
    "description": "A book of unsent letters from a late boyfriend unravels a love story, a secret, and a grief across Mumbai.",
    "is_sikkim": 0
  },
  {
    "id": "base_077",
    "title": "Things Fall Apart",
    "author": "Chinua Achebe",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 1958,
    "nation": "🇳🇬 Nigeria",
    "description": "The landmark African novel — Okonkwo watches his Igbo world collapse under colonialism. A foundational text of world literature.",
    "is_sikkim": 0
  },
  {
    "id": "base_078",
    "title": "Ishmael",
    "author": "Daniel Quinn",
    "genre": "Philosophy",
    "type": "Fiction",
    "year": 1992,
    "nation": "🇺🇸 USA",
    "description": "A gorilla teaches a man about civilisation's fatal story — dismantling humanity's assumptions about progress and dominance.",
    "is_sikkim": 0
  },
  {
    "id": "base_079",
    "title": "The Art of Racing in the Rain",
    "author": "Garth Stein",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2008,
    "nation": "🇺🇸 USA",
    "description": "Narrated by Enzo the dog — loyalty, racing metaphors, and the human capacity to find meaning in suffering and speed.",
    "is_sikkim": 0
  },
  {
    "id": "base_080",
    "title": "The Red Lion of the Hills",
    "author": "Ratanlal Brahmin",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2012,
    "nation": "🇮🇳 India",
    "description": "Historical fiction rooted in the Darjeeling Hills — navigating the Gorkhaland movement and mountain identity.",
    "is_sikkim": 0
  },
  {
    "id": "base_081",
    "title": "The Feeling May Remain",
    "author": "García Miralles",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2019,
    "nation": "🇪🇸 Spain",
    "description": "A graphic novel meditating on grief, time, and the residue of relationships — visually spare, emotionally resonant.",
    "is_sikkim": 0
  },
  {
    "id": "base_082",
    "title": "Kaalbudka Narkatha",
    "author": "Dr. Khemraj Sharma",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2015,
    "nation": "🇮🇳 India",
    "description": "A Nepali literary work from Sikkim — a significant text in the tradition of Sikkimese-Nepali literature.",
    "is_sikkim": 1
  },
  {
    "id": "base_083",
    "title": "Love Stories That Touched My Heart",
    "author": "Ravinder Singh (ed.)",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2012,
    "nation": "🇮🇳 India",
    "description": "An anthology of Indian love stories — tender, funny, heartbreaking, rooted in modern Indian life.",
    "is_sikkim": 0
  },
  {
    "id": "base_084",
    "title": "Khushwant Singh: Love & Misadventures",
    "author": "Khushwant Singh",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2015,
    "nation": "🇮🇳 India",
    "description": "Collected stories and reflections on love from one of India's great literary wits — frank, sensuous, unexpectedly tender.",
    "is_sikkim": 0
  },
  {
    "id": "base_085",
    "title": "The Princess and the Political Agent",
    "author": "Binodini",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2005,
    "nation": "🇮🇳 India",
    "description": "A classic Manipuri novel of colonial-era love between a princess and a British political agent — power, identity, and surrender.",
    "is_sikkim": 0
  },
  {
    "id": "base_086",
    "title": "50 Detective Stories",
    "author": "Vijaya Kumar (ed.)",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2012,
    "nation": "🇮🇳 India",
    "description": "A compendium of classic mystery short stories assembled for the Indian reader who loves a well-plotted crime.",
    "is_sikkim": 0
  },
  {
    "id": "base_087",
    "title": "And Then There Were None",
    "author": "Agatha Christie",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 1939,
    "nation": "🇬🇧 United Kingdom",
    "description": "The world's best-selling mystery — ten strangers, a nursery rhyme, and a killer among them. Christie's masterpiece of plotting.",
    "is_sikkim": 0
  },
  {
    "id": "base_088",
    "title": "The Invisible Man",
    "author": "H.G. Wells",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 1897,
    "nation": "🇬🇧 United Kingdom",
    "description": "A scientist turns himself invisible and descends into madness — a parable of isolation and the abuse of power.",
    "is_sikkim": 0
  },
  {
    "id": "base_089",
    "title": "Days at the Morisaki Bookshop",
    "author": "Satoshi Yagisawa",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2010,
    "nation": "🇯🇵 Japan",
    "description": "A gentle Tokyo novel set in Jinbocho book district — a young woman finds healing in her uncle's secondhand bookshop.",
    "is_sikkim": 0
  },
  {
    "id": "base_090",
    "title": "The Shadow Lines",
    "author": "Amitav Ghosh",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 1988,
    "nation": "🇮🇳 India",
    "description": "Memory, nationalism, and the arbitrary violence of borders — moving between Calcutta, London, and Dhaka across generations.",
    "is_sikkim": 0
  },
  {
    "id": "base_091",
    "title": "Paulo Coelho: The Zahir",
    "author": "Paulo Coelho",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2005,
    "nation": "🇧🇷 Brazil",
    "description": "A search for a missing wife becomes a spiritual journey across Central Asia — Coelho's meditation on obsession and liberation.",
    "is_sikkim": 0
  },
  {
    "id": "base_092",
    "title": "Paulo Coelho: Aleph",
    "author": "Paulo Coelho",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2010,
    "nation": "🇧🇷 Brazil",
    "description": "A pilgrimage across the Trans-Siberian Railway that becomes a journey through past lives and the act of loving.",
    "is_sikkim": 0
  },
  {
    "id": "base_093",
    "title": "A Thousand Splendid Suns",
    "author": "Khaled Hosseini",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2007,
    "nation": "🇦🇫 Afghanistan / 🇺🇸 USA",
    "description": "Two Afghan women across thirty years of war, oppression, and survival — a testament to female resilience.",
    "is_sikkim": 0
  },
  {
    "id": "base_094",
    "title": "Sea of Poppies",
    "author": "Amitav Ghosh",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2008,
    "nation": "🇮🇳 India",
    "description": "The first Ibis Trilogy volume — the opium trade, colonial India, and a diverse cast converging on one ship. Grand and linguistically extraordinary.",
    "is_sikkim": 0
  },
  {
    "id": "base_095",
    "title": "Blood of Fire",
    "author": "Amitav Ghosh",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2015,
    "nation": "🇮🇳 India",
    "description": "The third Ibis Trilogy volume — bringing the China opium wars to a close in a thrilling conclusion.",
    "is_sikkim": 0
  },
  {
    "id": "base_096",
    "title": "River of Smoke",
    "author": "Amitav Ghosh",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2011,
    "nation": "🇮🇳 India",
    "description": "The second Ibis Trilogy novel — Canton's foreign enclave as the First Opium War approaches.",
    "is_sikkim": 0
  },
  {
    "id": "base_097",
    "title": "The Seven Moons of Maali Almeida",
    "author": "Shehan Karunatilaka",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2022,
    "nation": "🇱🇰 Sri Lanka",
    "description": "The Booker Prize-winning dark comedy — a dead war photographer has seven moons to solve his own murder in 1990 Colombo.",
    "is_sikkim": 0
  },
  {
    "id": "base_098",
    "title": "Gun Island",
    "author": "Amitav Ghosh",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2019,
    "nation": "🇮🇳 India",
    "description": "A rare-books dealer follows the myth of the Gun Merchant from the Sundarbans to Venice — climate migration and ecological catastrophe.",
    "is_sikkim": 0
  },
  {
    "id": "base_099",
    "title": "Midnight's Children",
    "author": "Salman Rushdie",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 1981,
    "nation": "🇮🇳 India / 🇬🇧 UK",
    "description": "The Booker of Bookers — Saleem Sinai, born at India's midnight of independence, linked to all midnight children. A magic realist masterpiece.",
    "is_sikkim": 0
  },
  {
    "id": "base_100",
    "title": "A Game of Thrones",
    "author": "George R.R. Martin",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 1996,
    "nation": "🇺🇸 USA",
    "description": "The first volume of the epic fantasy saga — Westeros, the Iron Throne, and a new benchmark for political fantasy.",
    "is_sikkim": 0
  },
  {
    "id": "base_101",
    "title": "There's a Carnival Today",
    "author": "Indra Bahadur Rai",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2005,
    "nation": "🇮🇳 India",
    "description": "Stories by the father of Nepali literature in India — Rai's short fiction from Darjeeling and Sikkim.",
    "is_sikkim": 1
  },
  {
    "id": "base_102",
    "title": "Jiwan Rai",
    "author": "Jiwan Rai",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2014,
    "nation": "🇮🇳 India",
    "description": "A Nepali-language novel from Sikkim — identity, migration, and belonging in the hills of the eastern Himalayas.",
    "is_sikkim": 1
  },
  {
    "id": "base_103",
    "title": "The Blue Umbrella",
    "author": "Ruskin Bond",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 1974,
    "nation": "🇮🇳 India",
    "description": "Bond's beloved Himalayan novella — a small girl, a beautiful blue umbrella, and a covetous shopkeeper. A fable of greed, grace, and redemption.",
    "is_sikkim": 1
  },
  {
    "id": "base_104",
    "title": "The King's Harvest",
    "author": "Chetan Raj Shrestha",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2018,
    "nation": "🇮🇳 India",
    "description": "A Sikkimese literary novel — the weight of inheritance, land, and memory in a Himalayan community.",
    "is_sikkim": 1
  },
  {
    "id": "base_105",
    "title": "The Unforgettable Woman",
    "author": "Pankaj Giri",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2019,
    "nation": "🇮🇳 India",
    "description": "A Nepali literary work from Sikkim — portraits of women whose stories resist forgetting.",
    "is_sikkim": 1
  },
  {
    "id": "base_106",
    "title": "Golsimal",
    "author": "Pushpa Sharma",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2016,
    "nation": "🇮🇳 India",
    "description": "A Nepali-language novel from Sikkim — domestic life and the changing world of women in the hills.",
    "is_sikkim": 1
  },
  {
    "id": "base_107",
    "title": "The Eyes",
    "author": "Ashim Basnet",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2019,
    "nation": "🇮🇳 India",
    "description": "Poetry and short fiction from a young Himalayan voice exploring love, place, and the melancholy of mountain life.",
    "is_sikkim": 1
  },
  {
    "id": "base_108",
    "title": "Black, White and Grey",
    "author": "Parimal Dahal",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2016,
    "nation": "🇮🇳 India",
    "description": "Stories from Sikkim's literary scene — the grey zones of human morality and social life in the hills.",
    "is_sikkim": 1
  },
  {
    "id": "base_109",
    "title": "The Gurkha's Daughter",
    "author": "Prajwal Parajuly",
    "genre": "Fiction",
    "type": "Fiction",
    "year": 2012,
    "nation": "🇮🇳 India / 🇬🇧 UK",
    "description": "Eight stories of the Nepali diaspora — migration, identity, and Gorkha lives from Sikkim to New York.",
    "is_sikkim": 1
  },
  {
    "id": "base_110",
    "title": "India After Gandhi",
    "author": "Ramachandra Guha",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 2007,
    "nation": "🇮🇳 India",
    "description": "The definitive history of post-independence India — Guha's monumental narrative of the world's largest democracy from 1947 to the present.",
    "is_sikkim": 0
  },
  {
    "id": "base_111",
    "title": "Early India: From the Origins to AD 1300",
    "author": "Romila Thapar",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 2002,
    "nation": "🇮🇳 India",
    "description": "Thapar's landmark re-reading of ancient Indian history — challenging nationalist mythologies with rigorous scholarship.",
    "is_sikkim": 0
  },
  {
    "id": "base_112",
    "title": "India Since Independence",
    "author": "Bipan Chandra et al.",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 1999,
    "nation": "🇮🇳 India",
    "description": "The standard academic text on post-independence India — comprehensive and authoritative.",
    "is_sikkim": 0
  },
  {
    "id": "base_113",
    "title": "India's Struggle for Independence",
    "author": "Bipan Chandra et al.",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 1988,
    "nation": "🇮🇳 India",
    "description": "The defining academic history of India's freedom movement — from 1857 to 1947.",
    "is_sikkim": 0
  },
  {
    "id": "base_114",
    "title": "The Anarchy",
    "author": "William Dalrymple",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 2019,
    "nation": "🇬🇧 United Kingdom",
    "description": "Dalrymple's riveting account of the East India Company's violent seizure of the Mughal Empire — corporate colonialism on an epic scale.",
    "is_sikkim": 0
  },
  {
    "id": "base_115",
    "title": "The Last Mughal",
    "author": "William Dalrymple",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 2006,
    "nation": "🇬🇧 United Kingdom",
    "description": "The fall of Delhi in 1857 — told through the eyes of Bahadur Shah Zafar and the city's doomed poets.",
    "is_sikkim": 0
  },
  {
    "id": "base_116",
    "title": "The Dawn of Everything",
    "author": "David Graeber & David Wengrow",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 2021,
    "nation": "🇺🇸 USA / 🇬🇧 UK",
    "description": "A radical rethinking of human prehistory — challenging Rousseau and Hobbes to argue that our ancestors had far more political freedom.",
    "is_sikkim": 0
  },
  {
    "id": "base_117",
    "title": "Paul Johnson: Intellectuals",
    "author": "Paul Johnson",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 1988,
    "nation": "🇬🇧 United Kingdom",
    "description": "Exposing the private lives and moral failures of Rousseau, Marx, Tolstoy, and others who claimed to guide humanity.",
    "is_sikkim": 0
  },
  {
    "id": "base_118",
    "title": "India's Greatest Speeches",
    "author": "Nitin Agarwal (ed.)",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 2014,
    "nation": "🇮🇳 India",
    "description": "The speeches that shaped the Indian nation — from Vivekananda to Ambedkar, Nehru to Indira.",
    "is_sikkim": 0
  },
  {
    "id": "base_119",
    "title": "A Brief History of Modern India",
    "author": "Spectrum",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 2018,
    "nation": "🇮🇳 India",
    "description": "A comprehensive survey of modern Indian history from the 18th century to independence.",
    "is_sikkim": 0
  },
  {
    "id": "base_120",
    "title": "A Concise History of Modern Europe",
    "author": "Mason",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 1970,
    "nation": "🇬🇧 United Kingdom",
    "description": "A standard academic survey of European history from the French Revolution to the mid-20th century.",
    "is_sikkim": 0
  },
  {
    "id": "base_121",
    "title": "Mossad",
    "author": "Michael Bar-Zohar & Nissim Mishal",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 2012,
    "nation": "🇮🇱 Israel",
    "description": "The definitive insider account of Israel's legendary intelligence agency — twenty-six missions that shaped modern history.",
    "is_sikkim": 0
  },
  {
    "id": "base_122",
    "title": "Sikkim: A Political History of Autonomy to Democracy",
    "author": "Alex McKay",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 2015,
    "nation": "🇬🇧 United Kingdom",
    "description": "A meticulous political history of Sikkim from autonomous kingdom to Indian state — the pressures that led to the 1975 merger.",
    "is_sikkim": 1
  },
  {
    "id": "base_123",
    "title": "Empire of Tea: The Asian Leaf That Conquered the World",
    "author": "Markman Ellis, Richard Coulton & Matthew Mauger",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 2015,
    "nation": "🇬🇧 United Kingdom",
    "description": "The global history of tea — from Chinese imperial courts to British colonial expansion, a leaf that shaped empires.",
    "is_sikkim": 1
  },
  {
    "id": "base_124",
    "title": "Opening the Hidden Land",
    "author": "Paul Mullard",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 2011,
    "nation": "🇬🇧 United Kingdom",
    "description": "The Buddhist history and sacred geography of Sikkim — the idea of beyul and how it shaped the kingdom's identity.",
    "is_sikkim": 1
  },
  {
    "id": "base_125",
    "title": "The Guru Drinks Bourbon?",
    "author": "Dzongsar Jamyang Khyentse",
    "genre": "Spirituality",
    "type": "Non-Fiction",
    "year": 2016,
    "nation": "🇧🇹 Bhutan",
    "description": "A Bhutanese lama's irreverent, wise guide to the relationship between spiritual teacher and student — what it really means to follow a guru in the modern world.",
    "is_sikkim": 1
  },
  {
    "id": "base_126",
    "title": "Smash & Grab: Annexation of Sikkim",
    "author": "Sunanda K. Datta-Ray",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 1984,
    "nation": "🇮🇳 India",
    "description": "The controversial insider account of Sikkim's 1975 absorption into India — diplomacy, the Chogyal's resistance, and the end of a kingdom.",
    "is_sikkim": 1
  },
  {
    "id": "base_127",
    "title": "Sikkim: Requiem for a Himalayan Kingdom",
    "author": "Andrew Duff",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 2015,
    "nation": "🇬🇧 United Kingdom",
    "description": "A comprehensive narrative history of Sikkim's last decades — beautifully written, drawing on newly available archives.",
    "is_sikkim": 1
  },
  {
    "id": "base_128",
    "title": "The Royal History of Sikkim",
    "author": "Royal Household of Sikkim",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 1908,
    "nation": "🇮🇳 India",
    "description": "The official chronicle of the Namgyal dynasty — royal genealogy, religious foundations, and the history of the Himalayan kingdom. A primary source.",
    "is_sikkim": 1
  },
  {
    "id": "base_129",
    "title": "Gazetteer of Sikkim",
    "author": "H.H. Risley (ed.)",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 1894,
    "nation": "🇬🇧 United Kingdom",
    "description": "The colonial-era gazetteer — geography, ethnography, and natural history compiled by the British. An indispensable primary source.",
    "is_sikkim": 1
  },
  {
    "id": "base_130",
    "title": "The History of Bhutan",
    "author": "Karma Phuntsho",
    "genre": "History",
    "type": "Non-Fiction",
    "year": 2013,
    "nation": "🇧🇹 Bhutan",
    "description": "The first comprehensive English-language history of Bhutan — from mythological origins to the constitutional monarchy.",
    "is_sikkim": 1
  },
  {
    "id": "base_131",
    "title": "You Must Know Your Constitution",
    "author": "Fali S. Nariman",
    "genre": "Politics",
    "type": "Non-Fiction",
    "year": 2018,
    "nation": "🇮🇳 India",
    "description": "India's celebrated senior advocate makes the case for constitutional literacy as a civic duty.",
    "is_sikkim": 0
  },
  {
    "id": "base_132",
    "title": "The Battle of Belonging",
    "author": "Shashi Tharoor",
    "genre": "Politics",
    "type": "Non-Fiction",
    "year": 2020,
    "nation": "🇮🇳 India",
    "description": "Tharoor's authoritative examination of nationalism — from the French Revolution to today's toxic populisms.",
    "is_sikkim": 0
  },
  {
    "id": "base_133",
    "title": "Why I Am a Hindu",
    "author": "Shashi Tharoor",
    "genre": "Politics",
    "type": "Non-Fiction",
    "year": 2018,
    "nation": "🇮🇳 India",
    "description": "A personal intellectual defence of Hinduism as a civilisational ethos of pluralism — against Hindutva's distortions.",
    "is_sikkim": 0
  },
  {
    "id": "base_134",
    "title": "The Paradoxical Prime Minister",
    "author": "Shashi Tharoor",
    "genre": "Politics",
    "type": "Non-Fiction",
    "year": 2018,
    "nation": "🇮🇳 India",
    "description": "Tharoor's forensic political biography of Narendra Modi — rhetoric versus reality.",
    "is_sikkim": 0
  },
  {
    "id": "base_135",
    "title": "Pax Indica",
    "author": "Shashi Tharoor",
    "genre": "Politics",
    "type": "Non-Fiction",
    "year": 2012,
    "nation": "🇮🇳 India",
    "description": "Tharoor's blueprint for India's foreign policy in a multipolar world.",
    "is_sikkim": 0
  },
  {
    "id": "base_136",
    "title": "Unbreaking India",
    "author": "Sanjay Dixit",
    "genre": "Politics",
    "type": "Non-Fiction",
    "year": 2020,
    "nation": "🇮🇳 India",
    "description": "An IAS officer's examination of threats to India's constitutional order — Article 370, the CAA, and national integrity.",
    "is_sikkim": 0
  },
  {
    "id": "base_137",
    "title": "Viksit Bharat @2047",
    "author": "C.K. Mathew et al. (ed.)",
    "genre": "Politics",
    "type": "Non-Fiction",
    "year": 2023,
    "nation": "🇮🇳 India",
    "description": "A policy blueprint for India at 100 — governance reforms required for a Developed India by the centenary of independence.",
    "is_sikkim": 0
  },
  {
    "id": "base_138",
    "title": "Ten Judgements That Changed India",
    "author": "Zia Mody",
    "genre": "Politics",
    "type": "Non-Fiction",
    "year": 2013,
    "nation": "🇮🇳 India",
    "description": "Ten landmark Supreme Court rulings that reshaped law, society, and the balance of power in independent India.",
    "is_sikkim": 0
  },
  {
    "id": "base_139",
    "title": "India's Politics: A View from the Backbench",
    "author": "Bimal Jalan",
    "genre": "Politics",
    "type": "Non-Fiction",
    "year": 2007,
    "nation": "🇮🇳 India",
    "description": "Former RBI Governor's frank assessment of India's political economy — governance failures and institutional decay.",
    "is_sikkim": 0
  },
  {
    "id": "base_140",
    "title": "Of Occupation and Resistance",
    "author": "Ranjit Chaudhuri & Farad Shah",
    "genre": "Politics",
    "type": "Non-Fiction",
    "year": 2016,
    "nation": "🇮🇳 India",
    "description": "Essays on Kashmir and Northeast India — occupations, insurgencies, and the voices of those under the weight of the state.",
    "is_sikkim": 0
  },
  {
    "id": "base_141",
    "title": "Communalism: A Primer",
    "author": "Vijay Chandra",
    "genre": "Politics",
    "type": "Non-Fiction",
    "year": 2005,
    "nation": "🇮🇳 India",
    "description": "The history and dynamics of religious communalism in India — essential for understanding Hindu-Muslim tensions.",
    "is_sikkim": 0
  },
  {
    "id": "base_142",
    "title": "The RSS and the BJP",
    "author": "Various",
    "genre": "Politics",
    "type": "Non-Fiction",
    "year": 2010,
    "nation": "🇮🇳 India",
    "description": "The ideological and organisational relationship between the RSS and BJP — the Hindu nationalist ecosystem.",
    "is_sikkim": 0
  },
  {
    "id": "base_143",
    "title": "The Science of Revolution",
    "author": "Lenny Wolff",
    "genre": "Politics",
    "type": "Non-Fiction",
    "year": 1983,
    "nation": "🇺🇸 USA",
    "description": "A Marxist-Leninist analysis of revolution — theory of the vanguard party and conditions for social transformation.",
    "is_sikkim": 0
  },
  {
    "id": "base_144",
    "title": "Inked in India",
    "author": "Bibek Debroy & Anubha Bhonsle (ed.)",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2013,
    "nation": "🇮🇳 India",
    "description": "India through its tattoo traditions — body art as cultural identity, ritual, and resistance.",
    "is_sikkim": 0
  },
  {
    "id": "base_145",
    "title": "Modi: Mother, Where's My Country?",
    "author": "Anubha Bhonsle",
    "genre": "Politics",
    "type": "Non-Fiction",
    "year": 2014,
    "nation": "🇮🇳 India",
    "description": "Ground-level accounts of the 2002 Gujarat riots and their long aftermath — oral histories and the search for justice.",
    "is_sikkim": 0
  },
  {
    "id": "base_146",
    "title": "The Fiction of Fact-Finding",
    "author": "Manoj Mitta",
    "genre": "Politics",
    "type": "Non-Fiction",
    "year": 2014,
    "nation": "🇮🇳 India",
    "description": "A forensic dissection of India's fact-finding commissions and the gap between official record and reality.",
    "is_sikkim": 0
  },
  {
    "id": "base_147",
    "title": "Emergence and Continuity of Democracy in Sikkim",
    "author": "Dr. K.R. Chakaravarthi & Dr. Y.P. Nepal",
    "genre": "Politics",
    "type": "Non-Fiction",
    "year": 2015,
    "nation": "🇮🇳 India",
    "description": "An academic study of Sikkim's democratic evolution from chogyal's rule through merger to electoral consolidation.",
    "is_sikkim": 1
  },
  {
    "id": "base_148",
    "title": "Sikkim for Sikkimese",
    "author": "Jigme N. Kazi",
    "genre": "Politics",
    "type": "Non-Fiction",
    "year": 2009,
    "nation": "🇮🇳 India",
    "description": "A political argument for the special constitutional status of Sikkim's people — identity, rights, and statehood.",
    "is_sikkim": 1
  },
  {
    "id": "base_149",
    "title": "The Clash of Civilizations",
    "author": "Samuel P. Huntington",
    "genre": "Politics",
    "type": "Non-Fiction",
    "year": 1996,
    "nation": "🇺🇸 USA",
    "description": "The controversial thesis that post-Cold War conflicts will be defined by cultural and civilisational fault lines.",
    "is_sikkim": 0
  },
  {
    "id": "base_150",
    "title": "12 Rules for Life",
    "author": "Jordan B. Peterson",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 2018,
    "nation": "🇨🇦 Canada",
    "description": "Twelve principles for meaning, responsibility, and order drawn from mythology, evolutionary biology, and clinical experience.",
    "is_sikkim": 0
  },
  {
    "id": "base_151",
    "title": "The 48 Laws of Power",
    "author": "Robert Greene",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 1998,
    "nation": "🇺🇸 USA",
    "description": "Greene's provocative compendium of power's historical laws — Machiavelli, Sun Tzu, and centuries of courtly intrigue.",
    "is_sikkim": 0
  },
  {
    "id": "base_152",
    "title": "Think Like a Monk",
    "author": "Jay Shetty",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 2020,
    "nation": "🇬🇧 United Kingdom / 🇮🇳 India",
    "description": "Vedic wisdom distilled for modern life — purpose, mindfulness, and the ancient science of the mind.",
    "is_sikkim": 0
  },
  {
    "id": "base_153",
    "title": "Side Hustle",
    "author": "Chris Guillebeau",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 2017,
    "nation": "🇺🇸 USA",
    "description": "A 27-day plan for building a profitable secondary income without quitting your day job.",
    "is_sikkim": 0
  },
  {
    "id": "base_154",
    "title": "Do Epic Shit",
    "author": "Ankur Warikoo",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 2021,
    "nation": "🇮🇳 India",
    "description": "Principles on money, failure, habits, and relationships — unfiltered, practical, and relentlessly quotable.",
    "is_sikkim": 0
  },
  {
    "id": "base_155",
    "title": "Get Epic Shit Done",
    "author": "Ankur Warikoo",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 2023,
    "nation": "🇮🇳 India",
    "description": "Deeper dives into execution, time, and the discipline of building a life of intention rather than default.",
    "is_sikkim": 0
  },
  {
    "id": "base_156",
    "title": "The Success Sutra",
    "author": "Devdutt Pattanaik",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 2013,
    "nation": "🇮🇳 India",
    "description": "Indian mythology re-read through a business lens — what the Mahabharata teaches about leadership and ethics.",
    "is_sikkim": 0
  },
  {
    "id": "base_157",
    "title": "The 10-Day MBA",
    "author": "Steven Silbiger",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 1993,
    "nation": "🇺🇸 USA",
    "description": "The core curricula of America's leading business schools in one readable package.",
    "is_sikkim": 0
  },
  {
    "id": "base_158",
    "title": "Attitude Is Everything",
    "author": "Jeff Keller",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 1999,
    "nation": "🇺🇸 USA",
    "description": "Twelve steps to success built on the premise that changing one's attitude is the most powerful lever in a human life.",
    "is_sikkim": 0
  },
  {
    "id": "base_159",
    "title": "Thinking, Fast and Slow",
    "author": "Daniel Kahneman",
    "genre": "Science",
    "type": "Non-Fiction",
    "year": 2011,
    "nation": "🇮🇱 Israel / 🇺🇸 USA",
    "description": "Nobel laureate Kahneman's account of the two systems governing thought — intuition, deliberation, and the biases that distort decisions.",
    "is_sikkim": 0
  },
  {
    "id": "base_160",
    "title": "Good Vibes, Good Life",
    "author": "Vex King",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 2018,
    "nation": "🇬🇧 United Kingdom",
    "description": "A guide to self-love and intentional living — Vex King's story of rising from hardship as the framework.",
    "is_sikkim": 0
  },
  {
    "id": "base_161",
    "title": "NLP: The Essential Guide",
    "author": "Tom Hoobyar & Tom Dotz",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 2013,
    "nation": "🇺🇸 USA",
    "description": "A comprehensive introduction to Neuro-Linguistic Programming — modelling excellence, changing limiting beliefs.",
    "is_sikkim": 0
  },
  {
    "id": "base_162",
    "title": "Don't Believe Everything You Think",
    "author": "Omveer Talwar",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 2019,
    "nation": "🇮🇳 India",
    "description": "Practical tools for rewiring the mind from cognitive distortions — an Indian mindset-coach perspective.",
    "is_sikkim": 0
  },
  {
    "id": "base_163",
    "title": "Focus on What Matters",
    "author": "Various",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 2020,
    "nation": "🇮🇳 India",
    "description": "Cutting through distraction to life's true priorities — mindfulness and purposeful living for the modern reader.",
    "is_sikkim": 0
  },
  {
    "id": "base_164",
    "title": "Think Like the Minimalist",
    "author": "Chibag Gander & Sahil Vaidya",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 2019,
    "nation": "🇮🇳 India",
    "description": "An Indian perspective on intentional living — owning less creates the space for what truly matters.",
    "is_sikkim": 0
  },
  {
    "id": "base_165",
    "title": "Body: The Greatest Gadget",
    "author": "Thibaut Meurisse",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 2018,
    "nation": "🇫🇷 France",
    "description": "Optimising physical performance through sleep, nutrition, and movement — the human body as a finely tuned system.",
    "is_sikkim": 0
  },
  {
    "id": "base_166",
    "title": "Master Your Emotions",
    "author": "Thibaut Meurisse",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 2019,
    "nation": "🇫🇷 France",
    "description": "Understanding, accepting, and transforming difficult emotions — grounded in psychology and practical habit design.",
    "is_sikkim": 0
  },
  {
    "id": "base_167",
    "title": "The Practicing Mind",
    "author": "Thomas M. Sterner",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 2012,
    "nation": "🇺🇸 USA",
    "description": "A musician's philosophy of process over outcome — present-focused practice as the path to mastery.",
    "is_sikkim": 0
  },
  {
    "id": "base_168",
    "title": "Ikigai",
    "author": "Héctor García & Francesc Miralles",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 2016,
    "nation": "🇯🇵 Japan / 🇪🇸 Spain",
    "description": "The Japanese concept of a reason for being — the Okinawan secret to a long, purposeful life.",
    "is_sikkim": 0
  },
  {
    "id": "base_169",
    "title": "The Comfort Book",
    "author": "Matt Haig",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 2021,
    "nation": "🇬🇧 United Kingdom",
    "description": "Notes, lists, and short essays on what Haig has found comforting — an antidote to despair.",
    "is_sikkim": 0
  },
  {
    "id": "base_170",
    "title": "Brave New Words",
    "author": "Salman Khan",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2024,
    "nation": "🇺🇸 USA",
    "description": "Khan Academy's founder on how AI will transform education — a vision of personalised learning.",
    "is_sikkim": 0
  },
  {
    "id": "base_171",
    "title": "The Art of Being Alone",
    "author": "Renuka Gavrani",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 2023,
    "nation": "🇮🇳 India",
    "description": "A meditation on solitude and the radical act of enjoying one's own company in a world that fears loneliness.",
    "is_sikkim": 0
  },
  {
    "id": "base_172",
    "title": "Chicken Soup for the Indian Bride's Soul",
    "author": "Jack Canfield, Mark Victor Hansen & Raksha Bharadia",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 2008,
    "nation": "🇮🇳 India",
    "description": "Stories of transition, identity, and belonging for the Indian bride.",
    "is_sikkim": 0
  },
  {
    "id": "base_173",
    "title": "Don't Sweat the Small Stuff",
    "author": "Richard Carlson",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 1997,
    "nation": "🇺🇸 USA",
    "description": "One hundred strategies for keeping minor irritants in perspective — choosing what truly deserves our energy.",
    "is_sikkim": 0
  },
  {
    "id": "base_174",
    "title": "Journey to the Heart",
    "author": "Melodie Beattie",
    "genre": "Self-Help",
    "type": "Non-Fiction",
    "year": 1996,
    "nation": "🇺🇸 USA",
    "description": "Daily meditations for recovery and spiritual growth — gentle reflections on surrender, trust, and the heart.",
    "is_sikkim": 0
  },
  {
    "id": "base_175",
    "title": "Man's Search for Meaning",
    "author": "Viktor E. Frankl",
    "genre": "Philosophy",
    "type": "Non-Fiction",
    "year": 1946,
    "nation": "🇦🇹 Austria",
    "description": "Frankl's account of Auschwitz and logotherapy — the search for meaning as humanity's primary motivational force.",
    "is_sikkim": 0
  },
  {
    "id": "base_176",
    "title": "The Republic",
    "author": "Plato",
    "genre": "Philosophy",
    "type": "Non-Fiction",
    "year": -375,
    "nation": "🇬🇷 Greece",
    "description": "Plato's foundational dialogue on justice, the ideal state, and the philosopher-king. One of the most influential texts in Western thought.",
    "is_sikkim": 0
  },
  {
    "id": "base_177",
    "title": "Small Is Beautiful",
    "author": "E.F. Schumacher",
    "genre": "Philosophy",
    "type": "Non-Fiction",
    "year": 1973,
    "nation": "🇬🇧 United Kingdom",
    "description": "The landmark manifesto for human-scale economics — against gigantism, for economies built around people.",
    "is_sikkim": 0
  },
  {
    "id": "base_178",
    "title": "The Politics",
    "author": "Aristotle",
    "genre": "Philosophy",
    "type": "Non-Fiction",
    "year": -350,
    "nation": "🇬🇷 Greece",
    "description": "Aristotle's foundational text on political science — the state, justice, citizenship, and the ideal constitution.",
    "is_sikkim": 0
  },
  {
    "id": "base_179",
    "title": "Chanakya Neeti",
    "author": "Radhakrishnan Pillai",
    "genre": "Philosophy",
    "type": "Non-Fiction",
    "year": 2010,
    "nation": "🇮🇳 India",
    "description": "Chanakya's political and ethical maxims — ancient Indian wisdom on leadership, statecraft, and personal conduct.",
    "is_sikkim": 0
  },
  {
    "id": "base_180",
    "title": "The Art of War",
    "author": "Sun Tzu",
    "genre": "Philosophy",
    "type": "Non-Fiction",
    "year": -500,
    "nation": "🇨🇳 China",
    "description": "The world's most influential text on strategy — deception, positioning, and the nature of conflict.",
    "is_sikkim": 0
  },
  {
    "id": "base_181",
    "title": "Lives of the Stoics",
    "author": "Ryan Holiday & Stephen Hanselman",
    "genre": "Philosophy",
    "type": "Non-Fiction",
    "year": 2020,
    "nation": "🇺🇸 USA",
    "description": "Biographies of twenty-six Stoic philosophers from Zeno to Marcus Aurelius — their lives and the wisdom they offer.",
    "is_sikkim": 0
  },
  {
    "id": "base_182",
    "title": "A Brief History of Time",
    "author": "Stephen Hawking",
    "genre": "Science",
    "type": "Non-Fiction",
    "year": 1988,
    "nation": "🇬🇧 United Kingdom",
    "description": "Hawking's landmark popular science classic — the cosmos, black holes, the Big Bang, and the nature of time. One of the best-selling science books in history.",
    "is_sikkim": 0
  },
  {
    "id": "base_183",
    "title": "The Gene",
    "author": "Siddhartha Mukherjee",
    "genre": "Science",
    "type": "Non-Fiction",
    "year": 2016,
    "nation": "🇮🇳 India / 🇺🇸 USA",
    "description": "A sweeping history of the gene — from Mendel's peas to CRISPR, weaving science, ethics, and personal family history.",
    "is_sikkim": 0
  },
  {
    "id": "base_184",
    "title": "The Origin of Species",
    "author": "Charles Darwin",
    "genre": "Science",
    "type": "Non-Fiction",
    "year": 1859,
    "nation": "🇬🇧 United Kingdom",
    "description": "The book that changed everything — evolution by natural selection. The foundation of modern biology.",
    "is_sikkim": 0
  },
  {
    "id": "base_185",
    "title": "Freakonomics",
    "author": "Steven D. Levitt & Stephen J. Dubner",
    "genre": "Science",
    "type": "Non-Fiction",
    "year": 2005,
    "nation": "🇺🇸 USA",
    "description": "A rogue economist applies economic thinking to unexpected questions — the book that made economics thrilling.",
    "is_sikkim": 0
  },
  {
    "id": "base_186",
    "title": "A Short History of Nearly Everything",
    "author": "Bill Bryson",
    "genre": "Science",
    "type": "Non-Fiction",
    "year": 2003,
    "nation": "🇺🇸 USA / 🇬🇧 UK",
    "description": "Bryson's exhilarating tour of science — the Big Bang, quantum mechanics, genetics, and geology, told with infectious wonder.",
    "is_sikkim": 0
  },
  {
    "id": "base_187",
    "title": "The Tao of Physics",
    "author": "Fritjof Capra",
    "genre": "Science",
    "type": "Non-Fiction",
    "year": 1975,
    "nation": "🇦🇹 Austria / 🇺🇸 USA",
    "description": "The groundbreaking parallel between modern physics and Eastern mysticism — quantum mechanics and the Tao.",
    "is_sikkim": 0
  },
  {
    "id": "base_188",
    "title": "Schrödinger: What Is Life?",
    "author": "Erwin Schrödinger",
    "genre": "Science",
    "type": "Non-Fiction",
    "year": 1944,
    "nation": "🇦🇹 Austria / 🇮🇪 Ireland",
    "description": "A quantum physicist asks what makes life different from matter — anticipating the structure of DNA.",
    "is_sikkim": 0
  },
  {
    "id": "base_189",
    "title": "Relativity",
    "author": "Albert Einstein",
    "genre": "Science",
    "type": "Non-Fiction",
    "year": 1916,
    "nation": "🇩🇪 Germany / 🇺🇸 USA",
    "description": "Einstein's own accessible explanation of special and general relativity — written for the thoughtful lay reader.",
    "is_sikkim": 0
  },
  {
    "id": "base_190",
    "title": "Scale",
    "author": "Geoffrey West",
    "genre": "Science",
    "type": "Non-Fiction",
    "year": 2017,
    "nation": "🇬🇧 United Kingdom / 🇺🇸 USA",
    "description": "A physicist's discovery of universal laws governing the growth and death of organisms, cities, and companies.",
    "is_sikkim": 0
  },
  {
    "id": "base_191",
    "title": "Why We Die",
    "author": "Venki Ramakrishnan",
    "genre": "Science",
    "type": "Non-Fiction",
    "year": 2024,
    "nation": "🇮🇳 India / 🇬🇧 UK",
    "description": "The Nobel Prize-winning biologist's inquiry into ageing — the science of why we die and whether we should want to live longer.",
    "is_sikkim": 0
  },
  {
    "id": "base_192",
    "title": "Lifespan",
    "author": "David A. Sinclair",
    "genre": "Science",
    "type": "Non-Fiction",
    "year": 2019,
    "nation": "🇦🇺 Australia / 🇺🇸 USA",
    "description": "Harvard biologist Sinclair argues ageing is a disease — sirtuins, NAD+, and the science of living far longer.",
    "is_sikkim": 0
  },
  {
    "id": "base_193",
    "title": "Elementary Number Theory",
    "author": "Jesse Deason / Narinder Sharma",
    "genre": "Science",
    "type": "Non-Fiction",
    "year": 2010,
    "nation": "🇮🇳 India",
    "description": "An introduction to primes, divisibility, congruences, and Diophantine equations for the undergraduate student.",
    "is_sikkim": 0
  },
  {
    "id": "base_194",
    "title": "Dreams from My Father",
    "author": "Barack Obama",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 1995,
    "nation": "🇺🇸 USA",
    "description": "Obama's lyrical memoir of identity, race, and belonging — written before his political career, from Kenya to Hawaii to Chicago.",
    "is_sikkim": 0
  },
  {
    "id": "base_195",
    "title": "A Promised Land",
    "author": "Barack Obama",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2020,
    "nation": "🇺🇸 USA",
    "description": "The first volume of Obama's presidential memoir — his path to the White House and early years of his presidency.",
    "is_sikkim": 0
  },
  {
    "id": "base_196",
    "title": "Becoming",
    "author": "Michelle Obama",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2018,
    "nation": "🇺🇸 USA",
    "description": "Michelle Obama's deeply personal memoir — Chicago childhood, Princeton years, and life as First Lady.",
    "is_sikkim": 0
  },
  {
    "id": "base_197",
    "title": "Will",
    "author": "Will Smith with Mark Manson",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2021,
    "nation": "🇺🇸 USA",
    "description": "Will Smith's candid memoir — from West Philadelphia to global superstardom, wrestling with fear, ambition, and fame.",
    "is_sikkim": 0
  },
  {
    "id": "base_198",
    "title": "Losing My Virginity",
    "author": "Richard Branson",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 1998,
    "nation": "🇬🇧 United Kingdom",
    "description": "Branson's rollicking autobiography — Virgin Records, Virgin Atlantic, and the relentless rule-breaking spirit of an unconventional billionaire.",
    "is_sikkim": 0
  },
  {
    "id": "base_199",
    "title": "A Life in Diplomacy",
    "author": "Maharajkrishna Rasgotra",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2016,
    "nation": "🇮🇳 India",
    "description": "A distinguished Indian diplomat's memoir — inside accounts of India's most consequential foreign policy moments.",
    "is_sikkim": 0
  },
  {
    "id": "base_200",
    "title": "Nelson Mandela: A Biography",
    "author": "Martin Meredith",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 1997,
    "nation": "🇬🇧 United Kingdom",
    "description": "The definitive biography of Mandela — imprisonment, negotiation, presidency, and the long walk to freedom.",
    "is_sikkim": 0
  },
  {
    "id": "base_201",
    "title": "The Autobiography of Benjamin Franklin",
    "author": "Benjamin Franklin",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 1791,
    "nation": "🇺🇸 USA",
    "description": "America's founding polymath tells his own story — a model of self-improvement and civic virtue that shaped a nation.",
    "is_sikkim": 0
  },
  {
    "id": "base_202",
    "title": "My Inventions: The Autobiography of Nikola Tesla",
    "author": "Nikola Tesla",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 1919,
    "nation": "🇷🇸 Serbia / 🇺🇸 USA",
    "description": "Tesla's strange, visionary autobiography — the AC motor, the Tesla coil, and a mind decades ahead of its time.",
    "is_sikkim": 0
  },
  {
    "id": "base_203",
    "title": "Wings of Fire",
    "author": "A.P.J. Abdul Kalam",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 1999,
    "nation": "🇮🇳 India",
    "description": "India's People's President's own story — from Rameswaram to leading the missile programme. India's most-read autobiography.",
    "is_sikkim": 0
  },
  {
    "id": "base_204",
    "title": "The Dalai Lama: A Biography",
    "author": "Various",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2008,
    "nation": "🇮🇳 India / 🇨🇳 Tibet",
    "description": "A richly illustrated biography of His Holiness the 14th Dalai Lama — exile, activism, and Tibetan Buddhist wisdom.",
    "is_sikkim": 0
  },
  {
    "id": "base_205",
    "title": "The Great Derangement",
    "author": "Amitav Ghosh",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2016,
    "nation": "🇮🇳 India",
    "description": "Ghosh's brilliant essay arguing that literary fiction has failed to grapple with climate change — a challenge to storytellers.",
    "is_sikkim": 0
  },
  {
    "id": "base_206",
    "title": "The Anthropocene Reviewed",
    "author": "John Green",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2021,
    "nation": "🇺🇸 USA",
    "description": "John Green rates facets of the human-centred planet on a five-star scale — essays on meaning, history, and being alive.",
    "is_sikkim": 0
  },
  {
    "id": "base_207",
    "title": "Everybody Loves a Good Drought",
    "author": "P. Sainath",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 1996,
    "nation": "🇮🇳 India",
    "description": "Dispatches from India's poorest districts — exposing the gap between development rhetoric and lived poverty. A classic.",
    "is_sikkim": 0
  },
  {
    "id": "base_208",
    "title": "The Book Hunters of Katpadi",
    "author": "Pradeep Sebastian",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2012,
    "nation": "🇮🇳 India",
    "description": "A bibliophile's memoir and love letter to book-hunting in India — rare finds and the peculiar joy of the elusive volume.",
    "is_sikkim": 0
  },
  {
    "id": "base_209",
    "title": "The Nutmeg's Curse",
    "author": "Amitav Ghosh",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2021,
    "nation": "🇮🇳 India",
    "description": "Connecting the colonialism of the spice trade to today's climate crisis — nutmeg, conquest, and our planetary predicament.",
    "is_sikkim": 0
  },
  {
    "id": "base_210",
    "title": "Himalayan Arc",
    "author": "Namita Gokhale (ed.)",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2020,
    "nation": "🇮🇳 India",
    "description": "A rich anthology of writing on the Himalayas — history, ecology, mythology, and lived experience across the mountain arc.",
    "is_sikkim": 0
  },
  {
    "id": "base_211",
    "title": "Chai Time — A Darjeeling Tea Planter's Journey",
    "author": "Rajah Banerjee",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2014,
    "nation": "🇮🇳 India",
    "description": "The owner of Makaibari estate on biodynamic tea cultivation — a love letter to Darjeeling and the land.",
    "is_sikkim": 1
  },
  {
    "id": "base_212",
    "title": "Tibetan Caravans",
    "author": "Abdul Wahid Radhu",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2008,
    "nation": "🇨🇳 Tibet / 🇫🇷 France",
    "description": "The memoirs of a Muslim Tibetan merchant — cross-Himalayan trade routes and a vanished world before Chinese annexation.",
    "is_sikkim": 1
  },
  {
    "id": "base_213",
    "title": "The Teesta on the Run",
    "author": "Sarat Chandra Das",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2018,
    "nation": "🇮🇳 India",
    "description": "A narrative history of the Teesta river — ecology, culture, and the politics of Sikkim and West Bengal's contested river.",
    "is_sikkim": 1
  },
  {
    "id": "base_214",
    "title": "Bells of Shangri-La",
    "author": "Parimal Bhattacharya",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2017,
    "nation": "🇮🇳 India",
    "description": "Journey to Lhasa — scholars, spies, and invaders in Tibet across the Himalayan region.",
    "is_sikkim": 1
  },
  {
    "id": "base_215",
    "title": "Sikkim: A Step Away from Paradise",
    "author": "Thomas K. Shor",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2012,
    "nation": "🇺🇸 USA",
    "description": "An American writer's journey through Sikkim's landscape, culture, and spiritual geography.",
    "is_sikkim": 1
  },
  {
    "id": "base_216",
    "title": "A Brief Excursion into the Sacred Feminine",
    "author": "Mandeep Lama",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2020,
    "nation": "🇮🇳 India",
    "description": "Essays on gender, mythology, and the sacred feminine in Himalayan culture.",
    "is_sikkim": 1
  },
  {
    "id": "base_217",
    "title": "Lamas, Shamans and Ancestors",
    "author": "A. Balikci",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2008,
    "nation": "🇧🇪 Belgium",
    "description": "An anthropological study of Sikkim's religious practice — Tibetan Buddhism, shamanism, and Nepali ancestor worship.",
    "is_sikkim": 1
  },
  {
    "id": "base_218",
    "title": "The Mammoth Book of Travel in Dangerous Places",
    "author": "John Keay (ed.)",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 1996,
    "nation": "🇬🇧 United Kingdom",
    "description": "Adventure travel writing from history's most intrepid explorers — deserts, jungles, poles, and unmapped frontiers.",
    "is_sikkim": 0
  },
  {
    "id": "base_219",
    "title": "Desperately Seeking Shah Rukh",
    "author": "Shrayana Bhattacharya",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2021,
    "nation": "🇮🇳 India",
    "description": "An economist's field research into India's working women, conducted through their shared love of SRK.",
    "is_sikkim": 0
  },
  {
    "id": "base_220",
    "title": "Masala Lab",
    "author": "Krish Ashok",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2020,
    "nation": "🇮🇳 India",
    "description": "The science of Indian cooking — a software engineer deconstructs the chemistry of dal, tempering, and roti.",
    "is_sikkim": 0
  },
  {
    "id": "base_221",
    "title": "Whole Numbers and Half Truths",
    "author": "Rukmini S.",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2021,
    "nation": "🇮🇳 India",
    "description": "What data can and cannot tell us about modern India — statistics behind caste, gender, religion, and democracy.",
    "is_sikkim": 0
  },
  {
    "id": "base_222",
    "title": "Nexus",
    "author": "Yuval Noah Harari",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2024,
    "nation": "🇮🇱 Israel",
    "description": "A history of information networks from the Stone Age to AI — the power of connection, for better and worse.",
    "is_sikkim": 0
  },
  {
    "id": "base_223",
    "title": "The Argumentative Indian",
    "author": "Amartya Sen",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2005,
    "nation": "🇮🇳 India",
    "description": "Nobel laureate Sen's celebration of India's argumentative tradition — heterodoxy, pluralism, and democratic culture.",
    "is_sikkim": 0
  },
  {
    "id": "base_224",
    "title": "Poor Economics",
    "author": "Abhijit V. Banerjee & Esther Duflo",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2011,
    "nation": "🇮🇳 India / 🇫🇷 France",
    "description": "Nobel Prize-winning economists apply randomised trials to poverty — a new, evidence-based approach to development.",
    "is_sikkim": 0
  },
  {
    "id": "base_225",
    "title": "The Health of Nations",
    "author": "Karen Bartlett",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2018,
    "nation": "🇬🇧 United Kingdom",
    "description": "Global health systems and the social determinants of health — what makes populations sick or well.",
    "is_sikkim": 0
  },
  {
    "id": "base_226",
    "title": "Poverty, by America",
    "author": "Matthew Desmond",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2023,
    "nation": "🇺🇸 USA",
    "description": "The Pulitzer Prize-winning sociologist's argument that American poverty is deliberately maintained by the affluent.",
    "is_sikkim": 0
  },
  {
    "id": "base_227",
    "title": "Despite the State",
    "author": "M. Rajshekhar",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2021,
    "nation": "🇮🇳 India",
    "description": "A ground-level examination of how ordinary Indians navigate state failure across health, education, and livelihood.",
    "is_sikkim": 1
  },
  {
    "id": "base_228",
    "title": "Let's Make Dumplings!",
    "author": "Amano & Becan",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2021,
    "nation": "🇦🇺 Australia",
    "description": "A beautifully illustrated graphic cookbook for making Asian dumplings — from gyoza to baozi, with cultural history.",
    "is_sikkim": 0
  },
  {
    "id": "base_229",
    "title": "Scientists of India",
    "author": "Various",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2012,
    "nation": "🇮🇳 India",
    "description": "Profiles of India's great scientists from Aryabhata to APJ Abdul Kalam.",
    "is_sikkim": 0
  },
  {
    "id": "base_230",
    "title": "The Sterling Book of Quotations",
    "author": "Vijay Sharma",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2010,
    "nation": "🇮🇳 India",
    "description": "A comprehensive dictionary of quotations by theme — wit, wisdom, and memorable lines from the world's greatest minds.",
    "is_sikkim": 0
  },
  {
    "id": "base_231",
    "title": "What Your Doctor Doesn't Know About Nutritional Medicine",
    "author": "Ray D. Strand MD",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2002,
    "nation": "🇺🇸 USA",
    "description": "The evidence-based case for nutritional supplements and lifestyle medicine — challenging mainstream medical practice.",
    "is_sikkim": 0
  },
  {
    "id": "base_232",
    "title": "I, Vikke Khanna",
    "author": "Raksha Bharadia et al.",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2015,
    "nation": "🇮🇳 India",
    "description": "Stories from the life of Vikas Khanna — his Amritsar childhood, Michelin-starred journey, and Indian roots.",
    "is_sikkim": 0
  },
  {
    "id": "base_233",
    "title": "Prescription for Life",
    "author": "Medha Deshmukh Bhaskaran",
    "genre": "Non-Fiction",
    "type": "Non-Fiction",
    "year": 2012,
    "nation": "🇮🇳 India",
    "description": "A physician's guide to preventive medicine — lifestyle, nutrition, and mindset for a longer, healthier life.",
    "is_sikkim": 0
  }
];
